<?php

namespace Database\Seeders;

use App\Models\Permission;
use Illuminate\Database\Seeder;

class PermissionSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $permissions = [
            ['name' => 'permission_access', 'description' => 'Can access permissions page'],
            ['name' => 'permission_create', 'description' => 'Can create new permission'],
            ['name' => 'permission_show', 'description' => 'Can view a permission'],
            ['name' => 'permission_edit', 'description' => 'Can edit and update a permission'],
            ['name' => 'permission_delete', 'description' => 'Can delete a permission'],
            ['name' => 'role_access', 'description' => 'Can access roles page'],
            ['name' => 'role_create', 'description' => 'Can create new role'],
            ['name' => 'role_show', 'description' => 'Can view a role'],
            ['name' => 'role_edit', 'description' => 'Can edit and update a role'],
            ['name' => 'role_delete', 'description' => 'Can delete a role'],
            ['name' => 'user_access', 'description' => 'Can access users page'],
            ['name' => 'user_create', 'description' => 'Can create new user'],
            ['name' => 'user_show', 'description' => 'Can view a user'],
            ['name' => 'user_edit', 'description' => 'Can edit and update a user'],
            ['name' => 'user_delete', 'description' => 'Can delete a user'],
            ['name' => 'pump_owner_access', 'description' => 'Can access pump owners page'],
            ['name' => 'pump_owner_create', 'description' => 'Can create new pump owner'],
            ['name' => 'pump_owner_show', 'description' => 'Can view a pump owner'],
            ['name' => 'pump_owner_edit', 'description' => 'Can edit and update a pump owner'],
            ['name' => 'pump_owner_delete', 'description' => 'Can delete a pump owner'],
            ['name' => 'pump_detail_access', 'description' => 'Can access pump details page'],
            ['name' => 'pump_detail_create', 'description' => 'Can create new pump detail'],
            ['name' => 'pump_detail_show', 'description' => 'Can view a pump detail'],
            ['name' => 'pump_detail_edit', 'description' => 'Can edit and update a pump detail'],
            ['name' => 'pump_detail_delete', 'description' => 'Can delete a pump detail'],
            ['name' => 'pump_type_access', 'description' => 'Can access pump types page'],
            ['name' => 'pump_type_create', 'description' => 'Can create new pump type'],
            ['name' => 'pump_type_show', 'description' => 'Can view a pump type'],
            ['name' => 'pump_type_edit', 'description' => 'Can edit and update a pump type'],
            ['name' => 'pump_type_delete', 'description' => 'Can delete a pump type'],
            ['name' => 'compartment_access', 'description' => 'Can access compartments page'],
            ['name' => 'compartment_create', 'description' => 'Can create new compartment'],
            ['name' => 'compartment_show', 'description' => 'Can view a compartment'],
            ['name' => 'compartment_edit', 'description' => 'Can edit and update a compartment'],
            ['name' => 'compartment_delete', 'description' => 'Can delete a compartment'],
            ['name' => 'volume_access', 'description' => 'Can access volumes page'],
            ['name' => 'volume_create', 'description' => 'Can create new volume'],
            ['name' => 'volume_show', 'description' => 'Can view a volume'],
            ['name' => 'volume_edit', 'description' => 'Can edit and update a volume'],
            ['name' => 'volume_delete', 'description' => 'Can delete a volume'],
            ['name' => 'truck_identification_access', 'description' => 'Can access truck identifications page'],
            ['name' => 'truck_identification_create', 'description' => 'Can create new truck identification'],
            ['name' => 'truck_identification_show', 'description' => 'Can view a truck identification'],
            ['name' => 'truck_identification_edit', 'description' => 'Can edit and update a truck identification'],
            ['name' => 'truck_identification_delete', 'description' => 'Can delete a truck identification'],
            ['name' => 'truck_owner_access', 'description' => 'Can access truck owners page'],
            ['name' => 'truck_owner_create', 'description' => 'Can create new truck owner'],
            ['name' => 'truck_owner_show', 'description' => 'Can view a truck owner'],
            ['name' => 'truck_owner_edit', 'description' => 'Can edit and update a truck owner'],
            ['name' => 'truck_owner_delete', 'description' => 'Can delete a truck owner'],
            ['name' => 'pump_calibration_access', 'description' => 'Can access pump calibrations page'],
            ['name' => 'pump_calibration_create', 'description' => 'Can create new pump calibration'],
            ['name' => 'pump_calibration_show', 'description' => 'Can view a pump calibration'],
            ['name' => 'pump_calibration_edit', 'description' => 'Can edit and update a pump calibration'],
            ['name' => 'pump_calibration_delete', 'description' => 'Can delete a pump calibration'],
            ['name' => 'pump_calibration_measure_detail_access', 'description' => 'Can access pump calibration measure details page'],
            ['name' => 'pump_calibration_measure_detail_create', 'description' => 'Can create new pump calibration measure detail'],
            ['name' => 'pump_calibration_measure_detail_show', 'description' => 'Can view a pump calibration measure detail'],
            ['name' => 'pump_calibration_measure_detail_edit', 'description' => 'Can edit and update a pump calibration measure detail'],
            ['name' => 'pump_calibration_measure_detail_delete', 'description' => 'Can delete a pump calibration measure detail'],
            ['name' => 'pump_calibration_totaliser_reading_access', 'description' => 'Can access pump calibration totaliser readings page'],
            ['name' => 'pump_calibration_totaliser_reading_create', 'description' => 'Can create new pump calibration totaliser reading'],
            ['name' => 'pump_calibration_totaliser_reading_show', 'description' => 'Can view a pump calibration totaliser reading'],
            ['name' => 'pump_calibration_totaliser_reading_edit', 'description' => 'Can edit and update a pump calibration totaliser reading'],
            ['name' => 'pump_calibration_totaliser_reading_delete', 'description' => 'Can delete a pump calibration totaliser reading'],
            ['name' => 'certificate_access', 'description' => 'Can access certificates page'],
            ['name' => 'certificate_create', 'description' => 'Can create new certificate'],
            ['name' => 'certificate_show', 'description' => 'Can view a certificate'],
            ['name' => 'certificate_edit', 'description' => 'Can edit and update a certificate'],
            ['name' => 'certificate_delete', 'description' => 'Can delete a certificate'],
            ['name' => 'signature_pad_access', 'description' => 'Can access a signature pad on calibrations'],
            ['name' => 'meter_owner_access', 'description' => 'Can access meter owners page'],
            ['name' => 'meter_owner_create', 'description' => 'Can create new meter owner'],
            ['name' => 'meter_owner_show', 'description' => 'Can view a meter owner'],
            ['name' => 'meter_owner_edit', 'description' => 'Can edit and update a meter owner'],
            ['name' => 'meter_owner_delete', 'description' => 'Can delete a meter owner'],
            ['name' => 'meter_type_access', 'description' => 'Can access meter types page'],
            ['name' => 'meter_type_create', 'description' => 'Can create new meter type'],
            ['name' => 'meter_type_show', 'description' => 'Can view a meter type'],
            ['name' => 'meter_type_edit', 'description' => 'Can edit and update a meter type'],
            ['name' => 'meter_type_delete', 'description' => 'Can delete a meter type'],
            ['name' => 'meter_detail_access', 'description' => 'Can access meter details page'],
            ['name' => 'meter_detail_create', 'description' => 'Can create new meter detail'],
            ['name' => 'meter_detail_show', 'description' => 'Can view a meter detail'],
            ['name' => 'meter_detail_edit', 'description' => 'Can edit and update a meter detail'],
            ['name' => 'meter_detail_delete', 'description' => 'Can delete a meter detail'],
            ['name' => 'master_meter_access', 'description' => 'Can access master meter page'],
            ['name' => 'master_meter_create', 'description' => 'Can create new master meter'],
            ['name' => 'master_meter_show', 'description' => 'Can view a master meter'],
            ['name' => 'master_meter_edit', 'description' => 'Can edit and update a master meter'],
            ['name' => 'master_meter_delete', 'description' => 'Can delete a master meter'],
            ['name' => 'master_meter_totaliser_reading_access', 'description' => 'Can access master meter totaliser reading page'],
            ['name' => 'master_meter_totaliser_reading_create', 'description' => 'Can create new master meter totaliser reading'],
            ['name' => 'master_meter_totaliser_reading_show', 'description' => 'Can view a master meter totaliser reading'],
            ['name' => 'master_meter_totaliser_reading_edit', 'description' => 'Can edit and update a master meter totaliser reading'],
            ['name' => 'master_meter_totaliser_reading_delete', 'description' => 'Can delete a master meter totaliser reading'],
            ['name' => 'meter_calibration_totaliser_reading_access', 'description' => 'Can access meter calibration totaliser reading page'],
            ['name' => 'meter_calibration_totaliser_reading_create', 'description' => 'Can create new meter calibration totaliser reading'],
            ['name' => 'meter_calibration_totaliser_reading_show', 'description' => 'Can view a meter calibration totaliser reading'],
            ['name' => 'meter_calibration_totaliser_reading_edit', 'description' => 'Can edit and update a meter calibration totaliser reading'],
            ['name' => 'meter_calibration_totaliser_reading_delete', 'description' => 'Can delete a meter calibration totaliser reading'],
            ['name' => 'meter_calibration_access', 'description' => 'Can access meter calibrations page'],
            ['name' => 'meter_calibration_create', 'description' => 'Can create new meter calibration'],
            ['name' => 'meter_calibration_show', 'description' => 'Can view a meter calibration'],
            ['name' => 'meter_calibration_edit', 'description' => 'Can edit and update a meter calibration'],
            ['name' => 'meter_calibration_delete', 'description' => 'Can delete a meter calibration'],
            ['name' => 'meter_calibration_measure_detail_access', 'description' => 'Can access meter calibration measure details page'],
            ['name' => 'meter_calibration_measure_detail_create', 'description' => 'Can create new meter calibration measure detail'],
            ['name' => 'meter_calibration_measure_detail_show', 'description' => 'Can view a meter calibration measure detail'],
            ['name' => 'meter_calibration_measure_detail_edit', 'description' => 'Can edit and update a meter calibration measure detail'],
            ['name' => 'meter_calibration_measure_detail_delete', 'description' => 'Can delete a meter calibration measure detail'],
            ['name' => 'meter_calibration_certificate_access', 'description' => 'Can access meter calibration certificates page'],
            ['name' => 'meter_calibration_certificate_create', 'description' => 'Can create new meter calibration certificate'],
            ['name' => 'meter_calibration_certificate_show', 'description' => 'Can view a meter calibration certificate'],
            ['name' => 'meter_calibration_certificate_edit', 'description' => 'Can edit and update a meter calibration certificate'],
            ['name' => 'meter_calibration_certificate_delete', 'description' => 'Can delete a meter calibration certificate'],

            ['name' => 'calibration_product_access', 'description' => 'Can access calibration products page'],
            ['name' => 'calibration_product_create', 'description' => 'Can create new calibration product'],
            ['name' => 'calibration_product_show', 'description' => 'Can view a calibration product'],
            ['name' => 'calibration_product_edit', 'description' => 'Can edit and update a calibration product'],
            ['name' => 'calibration_product_delete', 'description' => 'Can delete a calibration product'],

            ['name' => 'calibration_standard_access', 'description' => 'Can access calibration standards page'],
            ['name' => 'calibration_standard_create', 'description' => 'Can create new calibration standard'],
            ['name' => 'calibration_standard_show', 'description' => 'Can view a calibration standard'],
            ['name' => 'calibration_standard_edit', 'description' => 'Can edit and update a calibration standard'],
            ['name' => 'calibration_standard_delete', 'description' => 'Can delete a calibration standard'],

            ['name' => 'signature_access', 'description' => 'Can access signatures page'],
            ['name' => 'signature_create', 'description' => 'Can create new signature'],
            ['name' => 'signature_show', 'description' => 'Can view a signature'],
            ['name' => 'signature_edit', 'description' => 'Can edit and update a signature'],
            ['name' => 'signature_delete', 'description' => 'Can delete a signature'],
        ];
        foreach ($permissions as $permission) {
            Permission::query()->firstOrCreate($permission, $permission);
        }
    }
}
